version: "3.9"

services:

  db:
    image: postgres:15
    container_name: fiesc-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fiesc-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - fiesc-network

  api:
    container_name: fiesc-backend
    build: 
      context: ../api-fiesc
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fiesc-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - fiesc-network

  frontend:
    container_name: fiesc-frontend
    build:
      context: ../frontend-react
      args:
        VITE_API_URL: http://api:8080
    ports:
      - "5173:80"
    networks:
      - fiesc-network

  cypress:
    container_name: fiesc-cypress
    build:
      context: ../tests-e2e
      dockerfile: Dockerfile
    working_dir: /e2e
    depends_on:
      - api
      - frontend
    environment:
      - frontendUrl=http://frontend:80
      - apiUrl=http://api:8080
    command: [npx cypress run"]
    networks:
      - fiesc-network

volumes:
  db-data:

networks:
  fiesc-network:
    driver: bridge
