version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fiesc-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiesc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../api-fiesc
      dockerfile: Dockerfile
    container_name: fiesc-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fiesc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend-react
    container_name: fiesc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
